### ISSUE TITLE
Code to create figures

### ISSUE THREAD

**Issue by estandiaa** [samirsaci/picking-route#2]
Hi Samir,
Thank you for making this code open source, it's super useful.

I did not see the code to generate the super nice warehouse figures you have in the readme (e.g., "Scenario 1: Picking routes with 1 order picked per wave", "Warehouse Layout with 2D Coordinates", "Scenario 2: Wave Picking applied to Scenario 1"). 

Did you make that code open source?

Thank you in advance.

**Comment by samirsaci** [comment]
> Hi Samir, Thank you for making this code open source, it's super useful.
> 
> I did not see the code to generate the super nice warehouse figures you have in the readme (e.g., "Scenario 1: Picking routes with 1 order picked per wave", "Warehouse Layout with 2D Coordinates", "Scenario 2: Wave Picking applied to Scenario 1").
> 
> Did you make that code open source?
> 
> Thank you in advance.

I used Photoshop and illustrator for these visuals.

For the animations of the picking path: https://towardsdatascience.com/animate-your-python-graphs-with-pillow-c1142b35c7f1
